### ISSUE TITLE
Core Audio

### ISSUE THREAD

**Issue by jenshk** [spotify/ios-sdk#103]
I am using SPTCoreAudioController in the old SDK. From what I can see there is no equivalent way of using Core Audio. Will this be possible in the future? Right now I am connecting a custom AudioUnit.

**Comment by Anders27** [comment]
I'm quite sure this will never happen since the new SDK seems to remote control the regular Spotify app (I haven't used it myself).
The new SDK is a very bad replacement for the old SDK. The only reason for the new SDK to exist must be that it's simpler to use and since most programmers knows very little about audio programming, Spotify probably hopes that this will create more apps supporting Spotify.
Let's hope we can persuade Spotify to continue to support the old SDK because that allows programmers to create apps that no other audio streaming company can offer.

**Comment by kkarayannis** [comment]
You are right that the new SDK doesn't provide access to the audio data. It only allows control of the Spotify app. There are no plans to support the old streaming SDK in the future.
