### ISSUE TITLE
Keep Spotify Connection While App Is Backgrounded

### ISSUE THREAD

**Issue by RomanScott** [spotify/ios-sdk#135]
I know this question has been asked a little bit before, but I was wondering if there were any ways (included or outside the Spotify SDK) that allow the app to continue interfacing with Spotify while the app is backgrounded.

On Android, this can be achieved by creating a BroadcastReceiver and listening to whenever the "music-play" notification. I was wondering if there was a similar concept for this in iOS. If not, is there a way to force my app to remain "active" while backgrounded?

The goal is to have my app perform certain functionality while the user plays songs in Spotify.

**Comment by kkarayannis** [comment]
Unfortunately, there isn't. iOS is very aggressive about suspending apps in the background. Since the audio is playing in the Spotify app (this SDK only controls the Spotify app), only that is given background execution privileges. Even Spotify is not allowed to execute in the background once playback stops.
