### ISSUE TITLE
Is it possible to shift between this SDK and the MediaPlayer SDK?

### ISSUE THREAD

**Issue by sslash** [spotify/ios-sdk#136]
Hi!

I’m trying to rebuild [Shift](https://apps.apple.com/gb/app/shift-lift-learn/id1406183218) using this SDK instead of the old streaming SDK. The app toggles between Spotify, and podcasts (where podcasts are played through the iOS MediaPlayer SDK). The problem is that as soon as I switch from Spotify to the other audio source, I seem to lose the connection to Spotify. Which is fine, but when I want to shift back, it fails to reconnect. This is the error I’m getting:

```
AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x28146a970 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}
```

So the question is: is it possible to switch between two audio sources like this with this SDK? It would be really neat as a lot of our users want offline support...

Any info on this would be sincerely appreciated! 🙏

**Comment by kkarayannis** [comment]
When playback stops, the audio session has ended so iOS will suspend the Spotify app. The Spotify app then has to shut down the app remote connection. In order to connect again, Shift would have to switch to the Spotify app again, like the first time it connected, in order to resume playback. Unfortunately there's no way to do that if the phone is locked or if your app is in the background.

One way to solve this would be to use Spotify for podcasts as well 🙂

**Comment by sslash** [comment]
Gotcha. Yeah, I'll keep using the old streaming library then. I agree could just use Spotify for podcasts as well, so that is something we are discussing. Thanks!
