### ISSUE TITLE
Spotify demo Objective-c login without Spotify App 

### ISSUE THREAD

**Issue by tiagomendesEye** [spotify/ios-sdk#15]
With demo provide in the new SDK for objective-c if the phone has Spotify app install it works well but  if the phone doesn't have the app Spotify installed I am having the error:

`"INVALID_CLIENT: Invalid redirect URI"
`

the option is set to: SPTDefaultAuthorizationOption

On the dashboard Redirect URIs is set:
spotify-login-sdk-test-app://spotify-login-callback

On the dashboard Bundle IDs is set:
com.spotify.sdk.SPTLoginSampleApp

On the app
static NSString * const SpotifyRedirectURLString = @"spotify-login-sdk-test-app://spotify-login-callback";

URL Schemes: spotify-login-sdk-test-app

ruby file
CLIENT_CALLBACK_URL = "spotify-login-sdk-test-app://spotify-login-callback"

Did I forget something?

**Comment by arirawr** [comment]
Hey @tiagomendesEye - are you seeing that error on the accounts.spotify.com webpage?

**Comment by arirawr** [comment]
Could you give me your client ID (*not* client secret)?

**Comment by tiagomendesEye** [comment]
Sure this is just test account.
Client ID e920c21bfc0b46569aa85e497788b62b

**Comment by arirawr** [comment]
I took a look behind the scenes - looks like your client ID has a redirect URI of `spotify-login-sdk-test-app://spotify-login-callback Remove` registered (with some extra text on the end). Could you log into the dashboard and make sure the redirect URI is entered correctly?

**Comment by arirawr** [comment]
Ok - great! Have you added `spotify` to your `LSApplicationQueriesSchemes` in info.plist?

```
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>spotify</string>
</array>
```

**Comment by tiagomendesEye** [comment]
I am just running the Demo version (objective-c) that is provided in the SDK.
I did check and yes there is the LSApplicationQueriesSchemes set with spotify
Any more suggestion? Are you able to reproduce my scenario?

**Comment by jackfreeman** [comment]
@tiagomendesEye you need to have a server to do the OAuth token swap. For testing purposes you can use the provided ruby script for the demo projects, please see the instructions in the Demo Projects readme [here](https://github.com/spotify/ios-sdk/tree/master/DemoProjects#how-to-use-the-provided-ruby-script).

For production you will want to set [these properties](https://github.com/spotify/ios-sdk/blob/master/DemoProjects/SPTLoginSampleApp/SPTLoginSampleApp/ViewController.m#L24-L25) to your server instead of localhost.

If you only want to control playback you do not need your own server and can instead use [this authorization flow](https://github.com/spotify/ios-sdk#using-the-built-in-app-remote-control-authorization-flow-recommended) (please note this flow requires the Spotify app to be installed)

**Comment by tiagomendesEye** [comment]
Its working!!!
Thank you @jackfreeman and @arirawr for the great feedback :)

I forgot to change form localhost to my local IP

```
configuration.tokenSwapURL = [NSURL URLWithString: @"http://192.168.1.73:1234/swap"];
configuration.tokenRefreshURL = [NSURL URLWithString: @"http://192.168.1.73:1234/refresh"];
```

**Comment by tiagomendesEye** [comment]
Its working!!!
Thank you @jackfreeman and @arirawr for the great feedback :)

I forgot to change form localhost to my local IP

configuration.tokenSwapURL = [NSURL URLWithString: @"http://192.168.1.73:1234/swap"];
configuration.tokenRefreshURL = [NSURL URLWithString: @"http://192.168.1.73:1234/refresh"];

**Comment by arirawr** [comment]
Great to hear! Have fun building with the SDK! :)
