### ISSUE TITLE
Waveform/envelope of a track

### ISSUE THREAD

**Issue by Czajnikowski** [spotify/ios-sdk#153]
Would be nice to show to the user some aproximation of waveform

**Comment by iKenndac** [comment]
Actually, this isn't correct. You can insert your own audio unit into the provided graph and use it to extract the data for a waveform before passing it on down the chain. 

Since this is already completely possible in the SDK right now, I'll close the issue.

I discussed this on Stack Overflow here if you need more detailed info: http://stackoverflow.com/questions/25394769/getting-pcm-audio-for-visualization-via-spotify-ios-sdk/25402724#25402724

**Comment by Czajnikowski** [comment]
@iKenndac I have checked and tried your answer on SO, but this is not what I'm looking for. My implementation requires showing the waveform of the whole track (before we will even play it). Is this kind of thing doable?
