### ISSUE TITLE
Autochange Equalizer based on the genre of the songs.

### ISSUE THREAD

**Issue by tjallilex** [spotify/ios-sdk#161]
Often I happen change from classical music to heavy metal or to the occasional pop-songs. It bothers me how I have to go to settings to change the equalizer. I mean, I listen to different genres multiple times a day. and linking the genre of the equalizer to any songs is not a hard task as far as I can think of. It is mostly a database task and a little python coding (or C++, not knowing in what language Spotify is in coded). It would be marvellous if I could automate the equalizer based on the genre of the songs, just by one switch on my phone. 
But this does in fact mean that if I go offline with my mobile, and am only able to listen to downloaded songs, it does indeed takes more space on my phone storage. 
Maybe the next step would be an actual change for every songs made by the artists. So the artist can recommend the settings in the equalizer.

Any opinions? 
Is it realistic? 
And is this idea actually worth any attention?

**Comment by kkarayannis** [comment]
Hi, it seems your issue is related to Spotify app, but this iOS SDK repo is for developers that want their application to interact with the Spotify app. If you want to report issues with the Spotify app, you can find information about how to contact us at https://support.spotify.com/us/article/how-can-i-contact-spotify
