### ISSUE TITLE
iOS streaming SDK closing

### ISSUE THREAD

**Issue by sbrighiu** [spotify/ios-sdk#168]
How can we playback playlists and tracks without iOS streaming SDK and without doing it through the Spotify Player app via AppRemote classes.

I want to create an app that has its own player similar to the app Noon Pacific, with curated playlists. Is there any way of doing it after 1st November 2019?

**Comment by kkarayannis** [comment]
Hi @sbrighiu,
There is no ability to play music outside of the Spotify app with the AppRemote SDK. That is intentional, and there is no replacement for the streaming SDK

**Comment by lyupko** [comment]
HI @kkarayannis,
We are going to release iOS app on AppStore with old iOS streaming SDK, Could you please provide the information about possible issues wich we could have if we do this?

**Comment by kkarayannis** [comment]
Hi @lyupko,
I would strongly advise against releasing a new app based on the deprecated SDK. It is unsupported and might stop working at any time, either because an iOS version breaks it or because access from the backend might be shut off. There are no plans for the latter for now, but we can't promise anything.
