### ISSUE TITLE
Mobile data has been consumed even when "Download using mobile data" is disabled

### ISSUE THREAD

**Issue by justfer11** [spotify/ios-sdk#170]
Spotify User: justfer11@outlook.com

Yesterday I was downloading my play lists using WiFi at home, then i went out for a couple of mins and not access to WiFi. After 15 mins i realized that i wasn't connected to WiFi but the playlists were been downloaded using my mobile data. 

I rechecked and the Download using mobile data wasn't enable:

![image](https://user-images.githubusercontent.com/56974762/67509775-5e87ef80-f659-11e9-848a-357178b4d2c1.png)

By then my mobile data has been consumed:
![image](https://user-images.githubusercontent.com/56974762/67509830-7a8b9100-f659-11e9-8f07-36f9360ce6a2.png)

I think we have a bug, i will try to reproduce  once i get more mobile data until Nov 7th :(

**Comment by kkarayannis** [comment]
Hi, it seems your issue is related to Spotify app for Android, but this iOS SDK repo is for developers that want their application to interact with the Spotify app. If you want to report issues with the Spotify app, you can find information about how to contact us at https://support.spotify.com/us/article/how-can-i-contact-spotify
