### ISSUE TITLE
Cannot get collaborative playlists

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#180]
Neither collaborative playlists that I have created or collaborated on are returned by `SPTRequest.playlistsForUserInSession` is there some other way to get them?

**Comment by possan** [comment]
We don't return return collaborative playlists when requesting a users' playlists, or when searching for playlists, if you know the url of a playlist however, you can access it. 

See: https://developer.spotify.com/web-api/get-list-users-playlists/

This is for security reasons since a collaborative playlist is basically open for anyone to manipulate, and making them searchable is not a good combination.

**Comment by thegreatmichael** [comment]
@possan would it be possible to reconsider this? perhaps there could be a scope for this? maybe a completely separate api call? If a user signs in with their spotify credentials and the app purports to show their playlists, they will not know why some (possibly all) lists are missing. would it be possible to make it so that third party apps cannot modify collaborative playlists?

**Comment by ryandt** [comment]
@thegreatmichael, I think it would be beneficial to return collaborative playlists when requesting users' playlists, but I also see the need for security. An alternative form of security to this issue would be to allow users to specify which users can edit a collaborative playlist. Instead of sending a link of the collaborative playlist to friends, users could explicitly provide usernames that are permitted to edit the playlist.

**Comment by thegreatmichael** [comment]
@ryandt indeed, but I can understand their reluctance to add on heavy access control features and UI...

**Comment by Zwaaan** [comment]
@possan Maybe it would be possible to have read access and no write? For my user case and perhaps for many else, read is all we need.

**Comment by thegreatmichael** [comment]
read-only would work for me too? perhaps collab playlists could have 2 URIs? one that allows modification that's not currently available via api bc of security, and another that shows up just like other playlists and does not allow modification?

**Comment by Zwaaan** [comment]
Yes, because my experience is that many users user collaborative lists, and many don't know the difference, so they will just be annoyed why their playlist is not visible.

**Comment by thegreatmichael** [comment]
I'm not sure how many of my users would use collab lists, (I bet spotify has data that can answer such a question), but I do, and some of my early users too.
