### ISSUE TITLE
App disconnected about every 30 sec and appRemote(_ appRemote: didDisconnectWithError:) called.

### ISSUE THREAD

**Issue by oleksandryevdokymov** [spotify/ios-sdk#204]
Hello i implemented integration logic from Spotify sdk.
And use NowPlayingView project from resources of ios-sdk like a example and logic almost the same. 
When playing music connection is ok.
But when i paused playback after about 30 seconds Spotify is disconnecting and `appRemote(_ appRemote: didDisconnectWithError:)` calling. And i receiving this error:

`Error Domain=com.spotify.app-remote Code=-1002 "Connection terminated." UserInfo={NSLocalizedDescription=Connection terminated., NSUnderlyingError=0x282386dc0 {Error Domain=com.spotify.app-remote.transport Code=-2001 "End of stream." UserInfo={NSLocalizedRecoverySuggestion=Reconnect to the Spotify app., NSLocalizedDescription=End of stream., NSLocalizedFailureReason=One of the streams has reached the end.}}, NSLocalizedRecoverySuggestion=Try to reconnect., NSLocalizedFailureReason=The Spotify app might have been suspended.}`

The same happens  in NowPlayingView app from Spotify sdk.
Please help with solutions!

**Comment by kkarayannis** [comment]
This is the expected behavior. iOS suspends all apps after 30 seconds. Spotify can keep running as long as the music is playing. When the music stops, the 30 second limit is in effect. Which is why you see app remote being disconnected.

**Comment by oleksandryevdokymov** [comment]
@kkarayannis thank you! I'm implemented wrapper using Spotify sdk on my custom Music player in app. And i think that it's bad user experience. Is there any suggestion? Or should i reconnect app every 30 seconds after i stopped music and Spotify is disconnected?

**Comment by kkarayannis** [comment]
You should reconnect when the user wants to play music again, because there is no way to reconnect without resuming playback.

**Comment by oleksandryevdokymov** [comment]
@kkarayannis Thank you!

**Comment by rahul-hinsu** [comment]
@kkarayannis  , As you said "iOS suspends all apps after 30 seconds". But when implementing SDK for remote controlling, we observed that it is being disconnected after only ~10 - 15 seconds. So may be it's not an issue of iOS. Because iOS might becomes more aggressive like suspending apps in about 10 seconds only when such a huge amount of applications are running. But there is no such a case like that.

Generally, other audio playback featured applications are working fine in background also. Like Apple music is working fine even with remote control from our App.

If you have any update on Remote issue, It would be great help for us. Thank you in advance.
