### ISSUE TITLE
No way to identify iTunes playlist

### ISSUE THREAD

**Issue by Kry256** [spotify/ios-sdk#211]
I load user playlist with 
```+(void)playlistsForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block```
method of ```SPTRequest``` class.
Basically I want to distinguish between 'Spotify playlists' and 'iTunes' local playlists, and for now I can't find any way to do this.

In addition when I try to play a track of an iTunes playlist, alway an error occurs.
Here the log:
**Error Domain=com.spotify.ios-sdk.playback Code=1001 "An unspecified playback error occurred." UserInfo=0x1674f330 {NSLocalizedDescription=An unspecified playback error occurred.}**

**Comment by ghassett** [comment]
I am also encountering this problem.  When playlists contain local files (e.g., from iTunes), and I make a call to [mySPTAudioStreamingController skipNext] that would skip to a local track, the player just stops playing.  There needs to be a way to filter out songs and playlists that are unplayable via SPTAudioStreamingController

**Comment by jarrodrobins** [comment]
+1 for this functionality. Ideally, we should be able to see this information on both SPTPartialPlaylist and SPTTrack so we can filter them out in our apps. It's currently a pretty crappy user experience in my app if someone gets an iTunes song, especially since we don't really know it's one until they try to play it. 

All it needs to be is a boolean flag on those two classes and we're golden, as far as I'm concerned. 

Another option could be just not to even send them down to the client and filter them out server side. Is there much point if users can't do anything with them, anyway?

**Comment by kennylovrin** [comment]
The local tracks have a uri that is "spotify:track:null" unless I am mistaken (can't remember exactly, but at least it contains 'null' somewhere in the uri ;)). We use that to filter out local tracks right now, it seems reliable so far.

I would think the problem with playlists is that you can mix local tracks and Spotify tracks in the same list, so not as obvious to just have a flag on those I'd imagine.

**Comment by jarrodrobins** [comment]
Ah, right you are. Looks like 'uri' starts with "spotify:local". Though, actually it's a little easier than that - "playableUri" is nil if it can't be played. Guess that sorts out one of my problems!

I had actually forgotten that you could mix iTunes and non-iTunes songs in a single playlist (particularly since I've never actually done it myself...) That certainly does complicate things, especially if you think about paging (ie, with a page size of 100 the only Spotify song in a playlist could be song 101). Regardless, some sort of way of quickly determining this would be ideal since realistically it'd affect basically every app using the SDK - it's hardly an uncommon use case.

**Comment by possan** [comment]
Yes, checking playableUri is a good way of doing this, i'm closing this, re-open if this is still an issue.

**Comment by msgilligan** [comment]
It sure would be nice to be able to get this information for a playlist. (e.g. how many local vs. nonlocal, or playable vs. non-playable tracks)
