### ISSUE TITLE
Playing a track with index > 99 does not work

### ISSUE THREAD

**Issue by johra** [spotify/ios-sdk#214]
When supplying a playlist and starting with:
-playTrackProvider:fromIndex:callback

It works fine until the track index exceeds 99. 
I have tried both setURI and queueURI with the same problem.

Is this a known issue?

**Comment by possan** [comment]
I just tried it with a regular playlist and that worked fine, using a custom track provider might be a problem though.. 

```
[self.player playTrackProvider:(id <SPTTrackProvider>)object fromIndex:150 callback:^(NSError *error) {}];
```

**Comment by johra** [comment]
Regular playlists works. But neither a custom track provider, PlayURIs, SetURIs  and QueueURIs seem to work properly with indexes > 99.

(I want to make a filtered selection from a playlist, re-sort it and play any track, any workaround?)

**Comment by johra** [comment]
@possan, are you able to reproduce the issue or is there something I can do to provide more information?

**Comment by possan** [comment]
We're aware of this issue, we're planning an update to the player api that will mitigate issues like these.

**Comment by shichongrui** [comment]
+1 to this. I am experiencing the same problem.

**Comment by lhammond** [comment]
+1

**Comment by possan** [comment]
I'm closing this, since the new api's are supporting a model of manipulating a list of tracks has been available since beta 7.

It currently supports a set of 100 tracks max, but you don't need to give it that many tracks at a time, if you want to play a huge playlist, you need to provide a subset of that and call `SPTAudioStreamingController replaceURIs:withCurrentTrack:callback:` to keep that list updated while also giving the player a current position within that list.

We'll try to provide an more complete example of how to do this and other more "advanced" playback mechanics in the future.
