### ISSUE TITLE
getSavedTracks parameters and implementations?

### ISSUE THREAD

**Issue by tnahvu** [spotify/ios-sdk#220]
Hi

I'm new to iOS and programming in general.  I got everything to work, including Heroku Oauth service, following the SDK tutorial. 

However, I would like to get a list of my saved tracks.  I am able to do this using good ol NSURLSession Datatask and parsing the JSON, but obviously I can't play the track without using Spotify SDK SPTAudioStreamingController...

I'm guessing that the getSavedTracks is the Session method to obtain the user's saved tracks, but I have no idea what to put in for the parameters and implementing it....

Sorry for such a newbie question here but I have searched for days now for answers and getting desperate.  Here is the github repo: https://github.com/tnahvu/spotifySDKtest
![screen shot 2015-01-22 at 4 37 48 pm](https://cloud.githubusercontent.com/assets/8174393/5867766/13cbb4a2-a255-11e4-8ee8-49350a7edf06.png)

I would really appreciate if anyone can offer any help!!

**Comment by iKenndac** [comment]
In ObjC it's typically a bad idea to use double-star references (`SPTSavedTrack **`) because they interfere with ARC and you won't know how big the buffer is. This is typically a C construct.

I'm going to point you to all the documentation you need and get you to 90% of where you need to go. The reason I'm doing this is because I really want to help you, but at Spotify we can't write your application for you or teach you Objective-C. 

First, I'm going to get rid of the `getSavedTracks:` method entirely. There's no need for it. 

What you need to do is use `SPTRequest` to request the saved tracks. You nearly got it right. However, if you [go to the documentation for `SPTRequest`](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTRequest.html#//api/name/savedTracksForUserInSession:callback:), you'll see that the `savedTracksForUserInSession:callback:` method doesn't return an `SPTSavedTrack` object, it returns an `SPTListPage` object. So, you need to change your call to reflect that. 

Once you have your `SPTListPage` object, you need to extract the tracks from it. If you [go to the `SPTListPage` documentation](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTListPage.html), you'll see that that it has a property called `items` that contains the items in that page. That property will contain the saved tracks. So, you need to change your `self.savedTracks = …` line to get the tracks from the `SPTListPage` property. 

Finally, the reason you get an `SPTListPage` back is because these APIs return paginated data. If you have more than 100 or so saved tracks, you'll need to keep fetching pages until you have them all. The `SPTListPage` documentation contains all of the information you need to do this.

Please take a detailed read of our documentation when you're stuck. It contains all the information you need to work with the SDK. You can find the root page online [here](https://developer.spotify.com/ios-sdk-docs/Documents/index.html), and it's also shipped with the SDK as a HTML package and embedded in the header files.

**Comment by tnahvu** [comment]
Thank you very much!  But I want to point out that getSavedTracks with the double pointers is not my method.  It is actually from the Spotify SDK.  

I have been reading through the docs and planned on using savedTracksForUserInSession but since I saw there was the getSavedTracks method, I thought that that would be the session method to use.  But if getSavedTracks is not needed, then I think I can manage. yay! 

Really, really appreciate your help!

**Comment by iKenndac** [comment]
Can you point out where `getSavedTracks` is, then? I work on the SDK and I can't see it anywhere.

**Comment by tnahvu** [comment]
That's the weird thing.  It will auto complete in Xcode but I can find it anywhere.  I tried option clicking it and nothing comes up.  
![screen shot 2015-01-23 at 1 58 49 am](https://cloud.githubusercontent.com/assets/8174393/5872717/74806fd8-a2a3-11e4-997f-ce0eb29d55a4.png)

Yeah, there's no way I would know to come up with a method using a double pointer and have never used NSRange.

**Comment by possan** [comment]
Look at `+(void)savedTracksForUserInSession:(SPTSession *)session callback:(SPTRequestCallback)block;` in `SPTRequest`

**Comment by tnahvu** [comment]
Cool, got it.  Thanks!

**Comment by iKenndac** [comment]
If you command-click a method in Xcode it'll take you to the definition. Maybe Xcode's autocomplete is just screwed-up — that happens more than it should.

**Comment by tnahvu** [comment]
Yeah, I've tried that.  Command-clicking getSavedTracks, playUsingSession, or any of the other Spotify SDK instance methods will not return anything.  Command-clicking the SPT Class Methods, however, will definitely take it to the definitions.

**Comment by tnahvu** [comment]
I now get a code 1012 error.

    -(void)fetchSavedTrack:(SPTSession*) session {
    
    [SPTRequest savedTracksForUserInSession:(SPTSession *)session callback:^(NSError *error, SPTListPage* trackList) {
        if (error != nil) {
            NSLog(@" track error = %@", error);
            return;
        }
        
        NSLog(@"This block is being run");
        
        self.savedTracks = [[NSArray alloc]initWithArray:trackList.items];
        NSLog(@"%@", self.savedTracks);
    }];
    }

I've also saw this link which had 1012 error: https://github.com/spotify/ios-sdk/issues/179, but this deals with playlist.

![screen shot 2015-01-23 at 3 21 09 pm](https://cloud.githubusercontent.com/assets/8174393/5884518/7eb1d030-a313-11e4-8ffa-f6c09119fbcd.png)

**Comment by tnahvu** [comment]
I get a 403: forbidden error now.  Session is good.  playUsingSession method can still be run.  I've looked through this link: https://github.com/spotify/ios-sdk/issues/93, but not sure if token and scopes apply in this case.  
![screen shot 2015-01-23 at 3 47 34 pm](https://cloud.githubusercontent.com/assets/8174393/5884812/9beb5df2-a317-11e4-809f-5ee18a660acd.png)
