### ISSUE TITLE
Can't get user library (saved content) broken down by artist or album.

### ISSUE THREAD

**Issue by mhuusko5** [spotify/ios-sdk#229]
Currently the only way to let a user browse their Spotify library (saved tracks) is to pull down all of their saved tracks (potentially all 20000), and then sort them into albums/artists client side.

It would be hugely valuable to be able to query what artists a user has saved instead, and then be able to query what albums of that artist they have saved, and then subsequently what tracks of that album (as is done in official Spotify clients).

**Comment by marcshilling** [comment]
+1. I NEED this functionality for my app. It takes entirely too long to page through all the saved tracks individually. Please add the ability to query saved artists or albums.

**Comment by skevy** [comment]
Any update on this? Potential workaround maybe? @iKenndac

**Comment by possan** [comment]
This is currently not supported by our API, i'll leave this open as an enhancement until we do.

**Comment by skevy** [comment]
So, it's not supported by the API or for this SDK? Because this functionality used to work with CocoaLibSpotify...

**Comment by iKenndac** [comment]
CocoaLibSpotify does not (and never did) support the user's library in any fashion — the user library was introduced last year and CocoaLibSpotify hasn't been updated since 2013.

**Comment by marcshilling** [comment]
@iKenndac true, but the equivalent functionality was at least possible. Before the "User Library" introduction, it was all about playlists. So for an app that wanted to basically learn about your music tastes, you would pull the entire "starred" playlist for example, and from there have a list of all the albums/artists in that playlist. For my starred playlist of several thousand songs, CocoaLibSpotify would return this info in SECONDS.

Now, to get this same info (all my songs from starred playlist are now in my "User Library"), I have to page through the [SPTRequest savedTracksForUserInSession] response over and over and over. This takes minutes now, not seconds - since the paged results are only roughly 20 songs per page.

**Comment by elmateo487** [comment]
I agree. This kind of functionality seems very important.

**Comment by iKenndac** [comment]
The functionality is there and available today. Small page sizes/long load times are a separate issue.

**Comment by mhuusko5** [comment]
The ability to get saved tracks is there. The ability to get saved albums/artists is not (e.g. "[SPTRequest savedArtistsForUserInSession]"), is it?

**Comment by marcshilling** [comment]
@mhuusko5 +1

There's a couple separate issues/enhancements at hand here, but either of these solutions will accomplish the same goal:
1. Improve [SPTRequest savedTracksForUserInSession] load times and paging - making it possible to then retrieve saved artists/albums (from each individual track) in an efficient manner.
2. Leave page size/load times the same, and allow us to request just Artists/Albums. This will be efficient because generally a massive collection of songs is composed of a relatively concise list of albums/artists.

**Comment by DOLOisSOLO** [comment]
+1 for retrieving user saved artist and album data.

**Comment by skiddle** [comment]
+1

**Comment by erdtman** [comment]
We are deprecating the iOS-Metadata library.

The source code of the iOS-Metadata library has been released and can be found [here](https://github.com/erdtman/spotify-ios-metadata/). Spotify will not continue to maintain the released source code.

Either you can select to use the web-api directly or use the new open source iOS-Metadata library.

I will close this issue now.

We are sorry for the inconvenience that this creates, but looking back we think this is the best path forward.
