### ISSUE TITLE
Remote connection lost after disconnecting from the Internet

### ISSUE THREAD

**Issue by AlexVedushev** [spotify/ios-sdk#29]
appRemote.playerAPI is setting to nil after lost Internet connection

**Comment by victor-m-1994** [comment]
I believe you'll have to reconnect the app remote before being able to access the playerAPI again

**Comment by AlexVedushev** [comment]
Проблема в том что нет возможности остановить проигрывание музыки без интернет соединения

**Comment by jackfreeman** [comment]
@AlexVedushev This will happen when using Airplane mode. Airplane mode is different than offline as it will close all connections. The "Offline Support" is only for when a user loses their data connection (due to being in a bad reception area, or a device without a cellular connection that's not on Wifi). 

Do not use Airplane mode for testing offline,.

**Comment by AlexVedushev** [comment]
I don't use airplane mode, I use wi-fi connection. (iOS 12 Xcode 10.0)
