### ISSUE TITLE
Problem to get the access token

### ISSUE THREAD

**Issue by LucasAbijmil** [spotify/ios-sdk#299]
I have a problem to get the access token. Indeed, when I call ```sessionManager.initiateSession(with: scopes, options: .default)``` I'm redirected to Spotify opening a modal to allow access to the account. Once accepted, Spotify redirects me to my application but doesn't provide me the access token. 

However, when I call ```appRemote.authorizeAndPlayURI("")```, the callback provides me with the access token (without opening the authorisation modal). 

Is this behavior normal ? How do I get the access token from the ```sessionManager.initiateSession``` callback ? 

If you need to see my implementation, let me know.

Thanks for your help.

**Comment by michaeldwilliams** [comment]
Same issue here. However, this seems to only be an issue when using the Spotify app to authorize. When I delete the app and authorize via the website, it works fine.

**Comment by LucasAbijmil** [comment]
Thank you for your response. I hope Spotify will update the SDK soon :-)

**Comment by siejkowski** [comment]
The `SPTSessionManager` is a class for managing the authorization flow described as *Authorization Code Flow* in [the documentation](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-flows).

Please notice that this flow **requires you to have a server** that manages exchanging the *authorization flow* for *access token* and *refresh token*. If your server also supports the token refresh endpoint, the `SPTSessionManager` instance will call it when needed for you. 

You'll need to set the `tokenSwapURL` and `tokenRefreshURL` in the `SPTConfiguration` so that they point to your server. The setup is described at [https://github.com/spotify/ios-sdk/blob/master/docs/auth.md](https://github.com/spotify/ios-sdk/blob/master/docs/auth.md)

The API that your server must support is at [https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/](https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/)

If you don't have a server and have little experience with a backend development than preparing this setup might seem like a big deal. But it's really not, mostly because your server doesn't need to keep any state. You can just use one of the serverless solutions like [Cloudflare Workers](https://workers.cloudflare.com) or [Azure Functions](https://azure.microsoft.com/en-us/services/functions/) or [AWS Lambda](https://aws.amazon.com/lambda/) or one of many others. They are usually free up to some (huge) number of requests per day.

I've been using Cloudflare Workers in my personal projects. I've posted the sample worker code [as the gist here](https://gist.github.com/siejkowski/e0774dd244fcc61e73558fedd466b79b) (please notice that encryption is missing as I don't want to misguide you suggesting some algorithm that I'm not sure is safe).
