### ISSUE TITLE
Connect to remote app without playing music

### ISSUE THREAD

**Issue by Matic1993** [spotify/ios-sdk#31]
Hi!

I would like to connect to remote app without playing music. So first I just want to get playlists and show them to user and when user selects the playlist then I would like to play the music.

So far it is partially working for me - it seems very unstable.

Sometimes everything is OK and remote app connects and sometimes I get errors:

`Error Domain=com.spotify.sdk.login Code=1 "invalid_grant" UserInfo={NSLocalizedDescription=invalid_grant}`

`AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x1cc04b400 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}`

I am doing standard procedure with session manager and backend for tokens swap.

So when delegate for established connection is called I connect to remote app.

Any ideas why is that happening on the random basis?

**Comment by Matic1993** [comment]
OK weird stuff is going on.

I saw that I have this problems if I play video in my app with `AVPlayer`

If I remove the video playing stuff then it seems that stuff works fine.

@jackfreeman can you please try this out and post your findings here.

Thanks!

**Comment by jackfreeman** [comment]
@Matic1993 you are probably experiencing "randomness" due to the state of the Spotify app in the background on the user's device. Music must be playing for the initial connection of the App Remote as that is the only way to guarantee Spotify will not be in a suspended state when backgrounded.

As for the `AVPlayer` issue, you need to ensure the audio session of your [app allows mixin of other audio sources](https://developer.apple.com/documentation/avfoundation/avaudiosession/categoryoptions/1616611-mixwithothers), otherwise your video will suspend the playback in Spotify.
