### ISSUE TITLE
SPTAudioStreamingController problem with replaceURIs

### ISSUE THREAD

**Issue by TimKreger** [spotify/ios-sdk#367]
I'm finding the method
 `-(void)replaceURIs:(NSArray *)uris withCurrentTrack:(int)index callback:(SPTErrorableOperationCallback)block;`

behaves the same regardless of what value withCurrentTrack is. It seems to replace all items in the track list, and then offsets the track index to the currentTrackIndex before the replace was made. 

I'm not sure what the actual behaviour should be but I'm thinking it should behave differently if the currentTrack value is different

**Comment by possan** [comment]
Yes, replaceURIs replaces the entire internal list of tracks, but sets your current position within it to e the value of withCurrentTrack

**Comment by CVertex** [comment]
Hi Spotify,

I'm encountering the same issue as @TimKreger. The withCurrentTrack parameter gets ignored all the time in beta 12.

So here's what I'm seeing...

1. Call playUris:[A,B,C,D] 
2. Playing starts at track A
3. During the middle of track A, call replaceUris:[W,X,Y,Z] withCurrentTrack:3
4. Press next track, then X starts playing

No matter what value withCurrentTrack is, X starts playing..
Is this expected behaviour? 

Thanks...

**Comment by ericn602** [comment]
The situation that @CVertex is describing is exactly what's happening to me. I have an internal array holding all the uris and deleting any specific uri before the currentTrackIndex in SPTAudioStreamingController messes up the indexes totally. I've tried to use the replaceUris method, however to no avail, as it seems the withCurrentTrack parameter is meaningless.

**Comment by indyfromoz** [comment]
Yes! I see the same thing. What does the withCurrentTrack parameter actually do? It does nothing for me :(

**Comment by erdtman** [comment]
replaceURIs has been removed
