### ISSUE TITLE
beta-10: fix for #380 broke playlist retrievals

### ISSUE THREAD

**Issue by steve-whitney** [spotify/ios-sdk#394]
On 'beta-10':
* fix for #380 works when no network available -- there is no crash (good)
* fix for #380 breaks retrieval of playlists when there IS a network available (bad)

I will post a proof-of-issue app shortly.

**Comment by TokyoBirdy** [comment]
Hi Steve, I know where the error coming from, and have a fix for it now, just need to be reviewed.

**Comment by AntonMeier** [comment]
I just noticed this as well and can confirm it. Great that it is being patched.

**Comment by steve-whitney** [comment]
@TokyoBirdy -- ok thanks.  Lawrence Kennedy asked for a proof-of-issue app, which I'll post soon.

**Comment by steve-whitney** [comment]
proof-of-issue app: https://github.com/steve-whitney/spt-ios-sdk-issue394

**Comment by TokyoBirdy** [comment]
@steve-whitney @AntonMeier  Just updated ios-sdk beta-10 for a few minutes ago. Please test it and let me know if the problem is solved. You should now get object when the network is good and get error when network occurs. Sorry for the trouble. And thanks for the quick feedback! Appreciate it.

https://github.com/spotify/ios-sdk/releases

**Comment by AntonMeier** [comment]
@TokyoBirdy , Thanks! I tested it and it works now. Although you still get a crash when doing a search for a song without internet connection. Any chance that it could be fixed as well? Would be nice to sort out these network related issues once and for all.

I get:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'

when using "performSearchWithQuery:queryType:accessToken:callback:".

**Comment by TokyoBirdy** [comment]
@AntonMeier Thanks for testing out! 
 Yeah it is pretty annoying to get a crash on search for songs without internet connection. And this should be fixed as well. But do you think you can create a new issue on this. So we can plan it in our sprint. 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'

when using "performSearchWithQuery:queryType:accessToken:callback:".

Thank you !

**Comment by steve-whitney** [comment]
Agree that new beta-10 (commit ea13...d49c) looks good with respect to playlists, both offline and online.  Thanks!

@TokyoBirdy : We also think that we are getting other 'data paramenter is nil' crashes (outside of playlist mgmnt).  Will report issues as we see them, but would be nice if Spotify could add sprint item for "audit ios sdk for 'data parameter is nil' crashes".

**Comment by steve-whitney** [comment]
closing this issue.

**Comment by TokyoBirdy** [comment]
@steve-whitney  cheers !
