### ISSUE TITLE
AppRemote connect results in TCP error

### ISSUE THREAD

**Issue by comills** [spotify/ios-sdk#40]
2018-10-09 15:30:08.046007-0600 Squffle[12505:4490112] AppRemote: Connecting...
2018-10-09 15:30:08.059834-0600 Squffle[12505:4490033] [] nw_connection_get_connected_socket 4 Connection has no connected handler
2018-10-09 15:30:08.061178-0600 Squffle[12505:4490033] TCP Conn 0x1c8360540 Failed : error 0:61 [61]

**Comment by jackfreeman** [comment]
@comills Music must be playing when you attempt to connect with App Remote, please see:
https://github.com/spotify/ios-sdk/issues/35
https://github.com/spotify/ios-sdk/issues/39

**Comment by comills** [comment]
So, was trying to figure a way around that requirement. Sounds like there isn't one. What if I only want to query library meta data without playing initially? Thx.

**Comment by dylanreich** [comment]
I am having this issue as well, even with music playing.

`2018-10-15 15:41:59.159423-0700 revo[17478:3599641] AppRemote: Connecting...
2018-10-15 15:41:59.161058-0700 revo[17478:3599614] [] nw_socket_handle_socket_event [C16.1:1] Socket SO_ERROR [61: Connection refused]`

**Comment by comills** [comment]
dylanreich: I must say, it's an asinine requirement that music must be playing. Further, it's even worse when that doesn't work either!

**Comment by jackfreeman** [comment]
@comills this is due to iOS restrictions. Spotify can't just be alive indefinitely in the background on the user's device if it's not doing anything. 

You can still auth without playing music, use the web api to fetch content, and then start playing music when the user has chosen something, please see this [comment](https://github.com/spotify/ios-sdk/issues/22#issuecomment-423938453) for how to achieve this.

**Comment by comills** [comment]
Jack,

I understand the IOS restrictions, however, can you have the Spotify app sleeping in a state (eg. listening for connections) and wake up when requested to? My app would like to query Spotify library meta data like it can with Apple Music. Playing a track is an optional, explicit event, not a requirement in my case. 

Thanks,
Tom

**Comment by jberglinds** [comment]
Had the same problem as @dylanreich.
Got the following error even though music was playing when connecting the remote:
```swift
2018-12-18 13:44:22.145361+0100 App[11666:4065494] [] nw_socket_handle_socket_event [C2.1:1] Socket SO_ERROR [61: Connection refused]
```

Apparently the issue was that
`sessionManager(manager: SPTSessionManager, didInitiate session: SPTSession)` was not called from the main thread after authentication returned. I did my `appRemote.connect()` connect in there.

Fix:
```diff
+    DispatchQueue.main.async {
        self.appRemote.connect()
+    }
```
