### ISSUE TITLE
Can't  promote SPTPartialArtist to a full artist object using SPTArtist.

### ISSUE THREAD

**Issue by nervouscat** [spotify/ios-sdk#413]
Hello,

Ive been attempting the following example : 
  SPTArtist *art = (SPTArtist*)([[self.searchMusicArray objectAtIndex:indexPath.row] objectAtIndex:0]);
 int count = [art.images count];

and I recieved the following error:
-[SPTPartialArtist images]: unrecognized selector sent to instance 0x17447fd80'

how can I convert SPTPartialArtist to SPTArtist?

Best regards,
Tarek M.

**Comment by jorgelsalas** [comment]
Hello! I've been dealing with the same issue for a couple of days. I know the issue was posted almost a month ago but I hope this can help you or at least someone else who has been trying to figure this out.

Turns out that the documentation for this sdk does not mention that there's a uri property in the SPTPartialArtist Class. You can use this to query Spotify and receive a SPTArtist instance (or a group of them). From your code I assume that you already have an array of SPTPartial artists. If that's the case then you can try the following:

```
NSURL* artistURI = [(SPTPartialArtist*)[mResults objectAtIndex:0] uri];
[SPTArtist artistWithURI:artistURI session:[self getSession] callback:^(NSError *error, id object) {
        if (error != nil) {
            NSLog(@"*** error while searching for full Artist %@", error);
            return;                
        }
        SPTArtist* fullArtist = (SPTArtist*)object;
        NSLog(@"These are the artist genres: \n%@", fullArtist.genres);
}];
```

Here, mResults is where I have stored my list of SPTPartialArtists and I use it to extract the URI of the first element.

The trick is to use the static methods of the SPTArtist Class to retrieve the full information. You have to send the artist URI which was extracted from the SPTPartialArtist instance, the session and the callback to execute upon getting the response.

There's also a convenience method that will allow you to get multiple SPTArtists by sending an array of URIs.

I hope this helps!
