### ISSUE TITLE
App size builds up

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-sdk#429]
I have set: player.diskCache = [[SPTDiskCache alloc] initWithCapacity:1024 * 1024 * 128];   //128MB

My app size is small <10MB however after several days of use my app size got up to 882MB! It must be the SDK's caching otherwise I have no explanation. Is there any way to limit or clear caches?

**Comment by loretoparisi** [comment]
A solution could be to let the app to check the cache status, since total disk occupancy for your app is sum of your app documents and caching, plus Spotify SDK caching, so you have a better chance to have more control over the disk usage doing:

```objective-c
- (void)checkAndPurgeDiskCache {
   NSError *error= nil;
   BOOL purged=mySPTDiskCache.evict(&error)
   if(error) NSLog(@"Unable to purge disk cache %d due to %@", purged, error.localizedDescription);
}
```

Of course as for the docs stated

```objective-c
/**
 * @brief Evict cache data.
 * @discussion Deletes cached data until the space occupied is <= `capacity`
 * @param error An error pointer that will contain an error if a problem occurred.
 * @return `YES` if eviction was successful, `NO` otherwise.
 */
- (BOOL)evict:(NSError **)error;
```

and so we should do drastically

```objective-c
- (void)checkAndPurgeDiskCache {
    if( mySPTDiskCache.size > mySPTDiskCache.capacity ) {
       NSError *error= nil;
       BOOL purged=mySPTDiskCache.clear(&error)
       if(error) NSLog(@"Unable to purge disk cache %d due to %@", purged, error.localizedDescription);
   }
}
```

You can also consider to clean cache on demand, rather than doing the check at every app load.

Let's consider that iOS is only firing two method, both related to low-memory conditions at run time:

- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application {
    // try to clean up as much memory as possible. next
}

and the notification from ```UIViewController``` presented at run time:

```UIApplicationDidReceiveMemoryWarningNotification```

that is fired when the app receives a warning about low memory conditions, so both these are about runtime memory occupancy.

There are a lot of discussions about app disk storage and memory usage, but you definitively I think it's up to you to do the checks, before purging your SPTDiskCache, the spotify disk cache, like:

```objective-c
- (uint64_t)freeDiskspace
{
    uint64_t totalSpace = 0;
    uint64_t totalFreeSpace = 0;

    __autoreleasing NSError *error = nil;  
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);  
    NSDictionary *dictionary = [[NSFileManager defaultManager] attributesOfFileSystemForPath:[paths lastObject] error: &error];  

    if (dictionary) {  
        NSNumber *fileSystemSizeInBytes = [dictionary objectForKey: NSFileSystemSize];  
        NSNumber *freeFileSystemSizeInBytes = [dictionary objectForKey:NSFileSystemFreeSize];
        totalSpace = [fileSystemSizeInBytes unsignedLongLongValue];
        totalFreeSpace = [freeFileSystemSizeInBytes unsignedLongLongValue];
        NSLog(@"Memory Capacity of %llu MiB with %llu MiB Free memory available.", ((totalSpace/1024ll)/1024ll), ((totalFreeSpace/1024ll)/1024ll));
    } else {  
        NSLog(@"Error Obtaining System Memory Info: Domain = %@, Code = %d", [error domain], [error code]);  
    }  

    return totalFreeSpace;
}
```

This last method, taken from https://code.google.com/p/toolsdotnet/wiki/iosOfflineMaps where you can find a lot of suggestion about how to check available free disk space for your app.

Hope this helps.

**Comment by erdtman** [comment]
Sorry for not getting back earlier. In an attempt to get a better overview of the issues we are cleaning out some of the older issues. If this issue is still a problem in the latest SDK please reopen this issue or open a new one.

**Comment by taomanwai** [comment]
Why evict is not found ?
