### ISSUE TITLE
How to set responseType=Code?

### ISSUE THREAD

**Issue by bsatorius** [spotify/ios-sdk#485]
I'm using swift. Tried a bunch of different ways to get a code rather than token back from the SDK's login method, but haven't had any success. Below is a snippet of code from my app:

    func spotifyInit() {
        spotifyAuthenticator.clientID = Constants.Spotify.ClientId
        spotifyAuthenticator.requestedScopes = [SPTAuthStreamingScope]
        spotifyAuthenticator.redirectURL = NSURL(string: Constants.Spotify.CallbackURL)
        
        let spotifyAuthentificationViewController = SPTAuthViewController.authenticationViewController()
        spotifyAuthentificationViewController.delegate = self
        spotifyAuthentificationViewController.modalPresentationStyle = UIModalPresentationStyle.OverCurrentContext
        spotifyAuthentificationViewController.definesPresentationContext = true
        
        presentViewController(spotifyAuthentificationViewController, animated: false, completion: nil)
    }

There's no property or function I can find that allows me to specify the responseType (I need a "code" rather than "token" for issuing refresh tokens). The Android sdk offers this settable property, but I've found no equivalent in the iOS sdk. What's the recommended approach?

**Comment by loretoparisi** [comment]
I have no knowledge in ```SPTAuth``` of a way to set the intermediate oAuth flow response of type ```code```.
But, you can always do this, since if you setup your own oAuth server, you can then use a client sdk to manage the oAuth flow, on iOS like this good one that I have used with Spotify web oAuth as well:

```NXOAuth2```  - https://github.com/nxtbgthng/OAuth2Client

Then you will something like

```objective-c
[[NXOAuth2AccountStore sharedStore] setClientID:kClientId
                                                 secret:kClientSecret
                                                  scope:[NSSet setWithObject:@"ALL"] ///// Here you can set CODE scope
                                       authorizationURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@/oauth/authorize",MXM_OAUTH_API_HOST]]
                                               tokenURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@/oauth/token",MXM_OAUTH_API_HOST]]
                                            redirectURL:[NSURL URLWithString:@"myapp://oauth/callback?"]
                                          keyChainGroup:@"MyApp"
                                         forAccountType:@"MyAccountTypeOAuth"];
```

Here https://github.com/spotify/ios-sdk/issues/453 I have posted a node.js oAuth server to handle connect request and the "code" type response's request as well.

So you can find the request with grant type ```authorization_code```

```javascript
spotifyAPI.postP("api/token",{}, qs.stringify({
        grant_type: "authorization_code",
        client_id: sp_id,
        client_secret: sp_secret,
        redirect_uri: sp_callback,
        code: code
    })).then(function() { ////...
})
```

that differs from the grant type ```refresh_token```

```javascript
spotifyAPI.post("api/token",{}, qs.stringify({
        grant_type: "refresh_token",
        client_id: sp_id,
        client_secret: sp_secret,
        refresh_token: refresh_token
    }))
    .then(function() { ////...
})
```

You can find this flow in the docs as well: https://developer.spotify.com/web-api/authorization-guide/

Another node.js full implementation is described here: https://github.com/spotify/ios-sdk/issues/193 in this  gist: https://gist.github.com/ahallora/f2d9c4c2a883977313ae

**Comment by bsatorius** [comment]
I appreciate the detailed comment, @loretoparisi. I actually have an oAuth service running and working well with the Android Spotify SDK. With the Android version, I'm using the native login methods that are supported by the SDK, and it all works fine. From what I understand, in the iOS sdk, we have no native support for initiating an auth-code based flow. It looks like we have to build this ourselves?

My hope was to implement a solution that does not require storing my Spotify client id and secret in the iOS app. That is surprising the iOS version of the SDK wouldn't provide this same feature--or maybe I've yet to find a working example, which is an iOS auth-code based flow without the use of storing the client secret on the device. 

Thanks again,
Brian

**Comment by loretoparisi** [comment]
@bsatorius I see. Since the oAuth flow is web based, you can implement everything using a oAuth client like the ```NXOAuth2```. This is the approach used on the Android SDK, there is no actual need for a native SDK for the Oauth, but just for the rtmp playback stuff.

To have an idea, you can look at the Web Player Demo called ```thirtify```, http://lab.possan.se/thirtify/
This made in JavaScript implements the Web oAuth flow, and you can see how the login flow is implemented here:

https://github.com/possan/webapi-player-example/blob/master/services/auth.js

**Comment by bsatorius** [comment]
Thanks for the pointer to NXOAuth2. One benefit to the approach you describe is that I can do away with the clunkier web view sign in for iOS and provide a native login screen to the user. As far as you know, is there and terms of use preventing me from bypassing the web-based Spotify login and using my own login screen with this OAuth library? 

I'll look over the Spotify TOS. 

Thanks for your help.

**Comment by erdtman** [comment]
To get the code grant flow you have to specify the tokenSwapURL for SPTAuth.

I will close this issue now if this does not solve the problem please reopen.
