### ISSUE TITLE
How to request top tracks

### ISSUE THREAD

**Issue by estock** [spotify/ios-sdk#495]
Is there a way to query for top tracks given the SPTArtist ?

**Comment by iGGNoRe** [comment]
Try this SPTArtist method:

[`+ createRequestForTopTracksForArtist:withAccessToken:market:error:`](https://developer.spotify.com/ios-sdk-docs/Documents/Classes/SPTArtist.html#//api/name/createRequestForTopTracksForArtist:withAccessToken:market:error:)

I haven't used it, but I'm assuming it's what you're looking for.

**Comment by loretoparisi** [comment]
@estock If you are talking about ```Top Lists``` you can refer to the WebAPI here:

https://github.com/loretoparisi/spotify-tvos-app-example

The ```SpotifyHelper``` class have this API method

```objective-c
-(void)fetchCategories:(NSDictionary*)options
           accessToken:(NSString*)accessToken
            completion:(void (^)(id results, NSError* error))completion;
```

As soon as you fetch the categories you can then get the once you want:

```objective-c
- (void)fetchCategory:(NSString*)categoryId options:(NSDictionary*)options
          accessToken:(NSString*)accessToken
          completion:(void (^)(id results, NSError* error))completion;
```

or you may want to fetch the playlists for this category:

```objective-c
- (void)fetchCategoryPlaylists:(NSString*)categoryId options:(NSDictionary*)options
                   accessToken:(NSString*)accessToken
                    completion:(void (^)(id results, NSError* error))completion;
```

At this point you are done and you can get the tracks in the playlists you need.
Since ```Beta12``` there are in the Spotify.framework new helpers api that let you execute Web APIs as well, and map JSON object response into SPTObjects.
Anyways it's a good exercise the try the web api directly.
