### ISSUE TITLE
Spotify login broken on iOS8

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#506]
With the latest beta SDK version, users with iOS8 can't login anymore.

Showing the `SPTAuthViewController` the SDK open Spotify App and appear this error:

![image1](https://cloud.githubusercontent.com/assets/1233649/11684422/c3c5113c-9e71-11e5-924e-893470821790.PNG)

This error seems to be related with #357 but i can't figure out a solution.

Please note:
In debugging, when the `SPTAuthViewController` it's coming up i have this console log:
`-canOpenURL: failed for URL: "spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"`
If i add the scheme 'spotify-action' in my app's info.plist i have the same problem also in iOS9

**Comment by JMSerruya** [comment]
Hi! Thanks for reporting, we will take a look at this internally and prioritize it.

**Comment by GabeJacobs** [comment]
Hm, this is working for me on the simulator

**Comment by bassntweeter** [comment]
Please post your info.plist. The error you receive suggests that there is a typo or some other issue with that file.

**Comment by martinobonfiglioli** [comment]
Basically I don't want to login with app switch to Spotify App. 
Yes, if I add `spotify-action` to my info.plist there's no error in the console log but I have the same problem also in iOS9.
Why if I use `SPTAuthViewController` the SDK switch to Spotify App and show a page with an error?

**Comment by bassntweeter** [comment]
OK. Then you have to implement the login via the webapi, https://developer.spotify.com/web-api/authorization-guide/. 
From now on switching to the Spotify App for authentication is default if the user has the Spotify installed.

**Comment by cloudjanak** [comment]
Can you add here simple request format ?

**Comment by martinobonfiglioli** [comment]
@bassntweeter when you introduced this feature? So by presenting `SPTAuthViewController` to login the SDK open Spotify App by default? Are you serious?!

Apple started to rejecting the App with switch login, so you introduced this web login by yours viewController to solve this issues #198 #242 #463

This is the comment inside `SPTAuthViewController `:
`/** A ViewController for managing the login flow inside your app. */`

Please don't close this issue because i think this is a real problem.

**Comment by bassntweeter** [comment]
@martinobonfiglioli 

#463 is rejection because you are encouraged to buy something outside of App Store. This will most likely not be an issue since the SSO flow will not present that sort of upsell.

#242 is rejection because you are encouraging users to sign up for a service that provides payment options outside of Apples universe. This one might always be a problem due to the nature of the rejection, regardless of the authentication method. 

#198 is rejection because of the bad UX of switching to a web browser for authentication. In this case we argue that the best UX is by switching to the Spotify app for a single sign on (not popping into a web view having to enter your credentials from scratch). There are several precedents with this UX flow accepted by Apple, one of them being how the Spotify app switches to the Facebook app for SSO, so we have good faith in this UX. 

I suggest that you send your app for review and see what Apple decides. If this turns out to be a problem for a majority of our partners we may revisit the decision regarding the SSO authentication.

P.S. If your users do not have the Spotify app installed, the authentication will happen just as before.

**Comment by bassntweeter** [comment]
@martinobonfiglioli based on the error you receive in the app it looks as though you have not registered all the details of your app on our developer site. Please review the information in https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/ under Creating Your Client ID, Secret and Callback URI and verify that you have entered all the information including your Bundle ID.

**Comment by JohnyBeG** [comment]
Hi,
Like martinobonfiglioli I have the same problem for login:

-canOpenURL: failed for URL: "spotify-action://" - error: "This app is not allowed to query for scheme spotify-action"

I followed the beginner tutorial but I can't login. Can you explain me what to do please ?

**Comment by michalumni** [comment]
1898:430062] -canOpenURL: failed for URL: "spotify-action://" - error: "(null)" I am getting this too, is this to do with the spotify-action needing to be in LSAApplicationQueriesSchemes, because I put it there too

**Comment by JohnyBeG** [comment]
@michalumni :+1:  Thank you but what have you written in LSAApplicationQueriesSchemes ?

**Comment by michalumni** [comment]
I just put String spotify-action and String spotify hoping that would let the urls through, similar to facebook login.

**Comment by lopezm1** [comment]
Same issue here. Is the -canOpenURL error a bug that exists then?

**Comment by nathanandersen** [comment]
+1

**Comment by aChase55** [comment]
+1

**Comment by vegrex** [comment]
+1

**Comment by agent-reed** [comment]
I too am having issues with: 
`-canOpenURL: failed for URL: "spotify-action://" - error: "(null)"`

To conform with Apple's new security policy, I added the string "spotify-action" in the LSAApplicationQueriesSchemes array in my application's info.plist file. However, I recieve the above error. 

Reference:
http://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/
