### ISSUE TITLE
Bitcode still not working on beta 14

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#511]
Maybe I am doing something wrong, but even on beta 14 it says the framework does not support bitcode. I get this error when trying to archive for the app store (when running it on my phone I don't get the error).

I get the error:

    ld: bitcode bundle could not be generated because '/Users/gabejacobs/Desktop/Anthem-iOS/Anthem/Spotify/Spotify.framework/Spotify(SPTAudioStreamingController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by loretoparisi** [comment]
@GabeJacobs that sounds strange! If you look at the segments you can see the __LLVM segments (due to bitcode) in:

https://github.com/spotify/ios-sdk/issues/445

Are you embedding Spotify.framework in another framework or putting it directly within the main app using "Link Binaries" Xcode Build Settings?

**Comment by GabeJacobs** [comment]
@loretoparisi so you can archive with bitcode enabled?

**Comment by doguhanokumus** [comment]
I am getting the exact same error when I try to archive my project as well. 

#445 also confirms that people are having problems with bitcode, so any update on this issue is appreciated

**Comment by marcshilling** [comment]
Can't archive because of this.

**Comment by loretoparisi** [comment]
Looking at the master and the release tag for the Beta-14, I can see that the bitcode commit `115365e7df876fe986743b87def86538ab6146d8` was not tagged, so you can find the bitcode on the master:

```bash
macbookproloreto:ios-sdk admin$ otool -l Spotify.framework/Versions/Current/Spotify | grep __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
```

but not on the tag: https://github.com/spotify/ios-sdk/tree/beta-14

**Comment by martinobonfiglioli** [comment]
@loretoparisi is right but I still have problem to archive my app because of **bitcode**

*ld: bitcode bundle could not be generated because 'Sdk/Spotify/Spotify.framework/Spotify(SPTAudioStreamingController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7*

This means that the framework isn't archived in the right way, I have found the same problems with my own framework and I have solved with this: http://stackoverflow.com/a/33581287/1197966

Please check it out!

**Comment by rickpern** [comment]
:+1: having same problem archiving

**Comment by abrasdev** [comment]
Having same problem archiving

**Comment by samgiagtzoglou** [comment]
Also still having this issue!

**Comment by loretoparisi** [comment]
+1

**Comment by jsanders67** [comment]
+1

**Comment by jsanders67** [comment]
@martinobonfiglioli did you get this framework to archive?

**Comment by ardaerzin** [comment]
will we ever be able to use this sdk in a proper way?

**Comment by abrasdev** [comment]
@GabeJacobs Did you find a way to make bitcode work? Or did you disable it?

**Comment by GabeJacobs** [comment]
@abrasdev disabled. It's been quite a while since a beta release from Spotify so fingers crossed they are still working on it.

**Comment by abrasdev** [comment]
@GabeJacobs yep. I hope so. I have 3 major issues with this SDK. Wifi handoff, runBackgroundLoop crash and Bitcode. The first two I believe I found a workaround. Now I need to see how I'm going to deal with the Bitcode issue.

**Comment by zackfletch00** [comment]
+1, Also having this problem with Bitcode.

**Comment by prestonwpope** [comment]
+1

**Comment by JMSerruya** [comment]
Hello!, this has been fixed in beta-16! Thanks for your patience and feel free to leave a comment if you've any further problems with bitcode!
https://github.com/spotify/ios-sdk/releases/tag/beta-16
