### ISSUE TITLE
Critical issue with " loginURLForClientId " - Swift project

### ISSUE THREAD

**Issue by RudyRosciglione** [spotify/ios-sdk#543]
I followed Brian Advent tutorial about implement Spotify login button. I did strictly all he did : https://www.youtube.com/watch?v=GeO00YdJ3cE -- But it sound like Xcode doesn't recognised "loginURLForClientId". I mean when I start to type it, Xcode doesn't show any autocomplete, accept "loginURL". the same for "declaredRedirectURL". 

<img width="1552" alt="screen shot 2015-12-18 at 23 36 18" src="https://cloud.githubusercontent.com/assets/1166152/11908843/27d5f824-a5e0-11e5-8955-1a59a02fde36.png">

Does any know if "loginURLForClientId" was change by something else? 

Export of the SPTAuth - the line who is wrong it declare here.. 

```
///----------------------------
/// @name Starting Authentication
///----------------------------

/**
 A URL that, when opened, will begin the Spotify authentication process.
 */
@property (readonly) NSURL *loginURL;


/**
 Returns a URL that, when opened, will begin the Spotify authentication process.

 @warning You must open this URL with the system handler to have the auth process
 happen in Safari. Displaying this inside your application is against the Spotify ToS.

 @param clientId Your client ID as declared in the Spotify Developer Centre.
 @param redirectURL Your callback URL as declared in the Spotify Developer Centre.
 @param scopes The custom scopes to request from the auth API.
 @param responseType Authentication response code type, defaults to "code", use "token" if you want to bounce directly to the app without refresh tokens.
 @return The URL to pass to `UIApplication`'s `-openURL:` method.
 */
+ (NSURL *)loginURLForClientId:(NSString *)clientId withRedirectURL:(NSURL *)redirectURL scopes:(NSArray *)scopes responseType:(NSString *)responseType;
```

**Comment by iGGNoRe** [comment]
Using `SPTAuth.defaultInstance()` only requires setting each value to their respective property, like so:

        auth.clientID = kClientId
        auth.redirectURL = NSURL(string:kCallbackURL)
        auth.tokenRefreshURL = NSURL(string:kTokenRefreshServiceURL)
        auth.tokenSwapURL = NSURL(string:kTokenSwapServiceURL)
        auth.sessionUserDefaultsKey = kSessionUserDefaultsKey
        auth.requestedScopes = [ . . . ]

Then simply using `let urlString = SPTAuth.defaultInstance().loginURL` (or `auth.loginURL` in your case) will return the URL you're looking for.

The only way that `+ loginURLForClientId:withRedirectURL:scopes:responseType:` will show up is if you aren't using an instance of SPTAuth. 

That tutorial being from February is pretty outdated. You'll definitely have to dig around in the code itself when something isn't working, because for some reason the documentation never seems to get updated with what's deprecated, it'll only say it in the code comments in the framework header files.

**Comment by RudyRosciglione** [comment]
To ne honest with you @iGGNoRe - i am a beginner so i don't exactly where to put your solution in my code. Yes i know, shame on me! Could you please show me how to perfectly write it? 

Thanks in advance.

**Comment by iGGNoRe** [comment]
The block I posted would go between your `let auth = . . . ` and `let loginURL= . . . `, so it'd be:

    let auth = SPTAuth.defaultInstance()

    auth.clientID = kClientId
    auth.redirectURL = NSURL(string:kCallbackURL)
    auth.tokenRefreshURL = NSURL(string:kTokenRefreshServiceURL)
    auth.tokenSwapURL = NSURL(string:kTokenSwapServiceURL)
    auth.requestedScopes = [SPTAuthStreamingScope ]

    let loginURL = auth.loginUrl

I removed the `auth.sessionUserDefaultsKey`, that was in my original comment, from this block since it looks like something you weren't using in your tutorial and remember to make sure to go through everything and know what it's doing. Don't just copy/paste this. It's basically just a more verbose way of doing what your tutorial was showing you, but it's important to understand what's happening and not just follow tutorials. I'm also learning the SDK and iOS dev in general, but this happened to one part I've gotten to understand.

**Comment by RudyRosciglione** [comment]
I totally agreeing with you. But i have to say for that part, i get really lost. Thanks anyway for your help.  I didn't copy and paste your lignes i just needed the position of them. I was kind of afraid to create a new issue. Now that part is working i have to declare in the AppDelegate.swift that :

> When the login success then hide the loginViewController to access to the application.

**Comment by JohnyBeG** [comment]
@iGGNoRe : I tried your SFVC-Spotify-Login from your github but I can't login. I filled all elements but when in Safari, I can't return to the app. Do you know why ?
Moreover you quoted here to use : 

auth.tokenRefreshURL = NSURL(string:kTokenRefreshServiceURL)
auth.tokenSwapURL = NSURL(string:kTokenSwapServiceURL)

but it's not used in your app. Why ?
The token paragraph disappeared from spotify tutorial

**Comment by iGGNoRe** [comment]
@JohnyBeG Hmm, I'm not sure why it wouldn't work if everything is filled out correctly. Create an issue over on [the SFVC login repo](../../../iGGNoRe/SFVC-Spotify-Login) so we aren't filling Spotify's up with unrelated comments and I'll try to help figure it out!

The SFVC-Spotify-Login example was purely an authentication sample using a new iOS 9 feature, and doesn't do anything with session renewals or token swaps so those are left out just because they aren't used in that app. The absence of the URLs should have no effect on authenticating, because they have to do only with session persistence (so renewing the session once it expires).
