### ISSUE TITLE
loginURLForClientId(_:) is not working in the last iOS SDK version.

### ISSUE THREAD

**Issue by emmanuelcu** [spotify/ios-sdk#588]
Hi!...

I am try to use the SDK for iOS for an application made in swift. The problem is when I make a call to the method loginURLForClientId(_:) it is not recognized or implemented in the last version of the Framework.

Someone could help to guide me?..

Thanks.

**Comment by jakereps** [comment]
That hasn't worked since I started messing around with this SDK, probably two or three versions ago at least, just set your `SPTAuth.defaultInstance()` variables individually using `SPTAuth.defaultInstance().clientID` etc... and then just call `SPTAuth.defaultInstance().loginURL`, which will return your properly built URL.

**Comment by DmytroAnkudinov** [comment]
There are two methods `loginURLForClientId` in the Spotify Metadata framework, both of them contain more than one parameter as of Beta24.
