### ISSUE TITLE
Enhancement request - Make “Fast App Switching” optional

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#692]
“Fast App Switching” (FAS) gives a bad user experience for apps that doesn’t have the automatic “token swap refresh” stuff. 
It may also irritate Apple and cause trouble when updating apps.

Even though I have my own web site hosted by a commercial web hosting company, I could never get the “token swap refresh” stuff to work so for now I have given up on that. 
For my users that means that the session expires every hour and the SPTAuthViewController is displayed for a brief moment. It’s not a very good user experience but it’s much much better than FAS.

So I would suggest to make it optional using FAS or not.

**Comment by NOlivNeto** [comment]
You could try setting the alpha of the auth view controller to zero and add a small progressbar while it is "displayed".

Not good, I know, but it's better than the blank view controller appearing for a moment.

**Comment by erdtman** [comment]
Hi, we cannot change the time to live for the token since it would be a security risk.

If you have trouble setting up the token swap and refresh back-end have a look at this project
https://github.com/simontaen/SpotifyTokenSwap

Alternatively it is possible to implement the swapping and refresh directly in the client even though it is strongly discurraged.
