### ISSUE TITLE
audioStreaming:didStopPlayingTrack bugs/issue

### ISSUE THREAD

**Issue by drew55** [spotify/ios-sdk#709]
Hi team!  

When the `SPTAudioStreamingPlaybackDelegate` call `audioStreaming:didStopPlayingTrack` is made by the `SPTAudioStreamingController` instance, there are two issues:

1) `:didStopPlayingTrack` is sometimes called _before_  `:didChangeToTrack` as well as before  `:didStartPlayingTrack` (instead of _after_)

2) when it _is_ called, SPTAudioStreamingController's  `currentPlaybackPosition` sometimes return 0 (presumably because the player is in an intermediate state)

It would be huge to resolve one or both of these issues.

This issue matters because we want to be able to store the play position of the outgoing item so we can resume from it at a later time.  Yes, there are hack work arounds, but they're not reliable since there's no reliable way to know when a track has run out on its own or is switching because of user intervention.  We could poll the player, but this is 2016 and my skin crawls at doing polling, especially since this sort of stuff eats away at battery efficiency.  

Thanks,
Drew
SoundSpectrum

**Comment by NOlivNeto** [comment]
@drew55 If you want reliability with this SDK, I'm afraid you're out of luck. But I'll try to help

1) `didStopPlayingTrack` is made to be called before `didChangeTrack`. It's in their documentation:

> `audioStreaming(audioStreaming: SPTAudioStreamingController!, didStopPlayingTrack trackUri: NSURL!)` Called **before** the streaming controller begins playing another track

2) `currentPlaybackPosition` is zero because the playback position on a stopped track is... Well... None. It's not being played. So it does not have a playback position.

I think to achieve what you want you need to use `didChangePlaybackStatus` and treat the playback status and position. The `stop` methods are for when the track has completely stopped, both by reaching its end or being stopped manually with `func stop(block: SPTErrorableOperationCallback)` (Beware of `stop()`, as it stops the whole player, not the playback)

If I misunderstood something, please clarify your question.
Good luck.

**Comment by drew55** [comment]
I appreciate your time to help.

I'm seeing here that `:didStopPlayingTrack:` is being called when a new item is set to start playing while an existing one is playing (not if a track just reaches the end or `stop` is called).  So the only way I have so far is to manually track what I start playing and if I see an item finish when `playURIs:` _hasn't_ been called then I say the track has completed normally.  It's just rather hackish and there are race condition cases where it can be defeated.  :(

**Comment by NOlivNeto** [comment]
@drew55 This calls before the track reach end are probably because the stream of the playback has finished, but not necessarily the audio playback has. It'll depend of the buffer... It's not reliable at all for your use. If think you could do rather well with the `didChangePlaybackStatus` for your case, I've done something like that and it worked.

But, like I said, we're out of luck if we need reliability. Let's hope things get better soon.

**Comment by d-kunin** [comment]
Closing since audioStreaming:didStopPlayingTrack will be removed, see https://github.com/spotify/ios-sdk/issues/716
