### ISSUE TITLE
Beta 20: `playURI: startingWithIndex: callback:` - first play always results in 'operation failed due to an unspecified issue'

### ISSUE THREAD

**Issue by NathanWalker** [spotify/ios-sdk#715]
The first play on a url like this `spotify:track:58s6EuEYJdlb0kO7awm3Vp` being passed to `playURI: startingWithIndex: callback:` (index always set to `0`) will always result in this initial error:

> Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo={NSLocalizedDescription=The operation failed due to an unspecified issue.}

After that, all play calls will work just fine, but always the first play will fail with that error initially.

This may be related to the fact that the API I think I need to use is `playURI: callback:` which apparently has been removed: https://github.com/spotify/ios-sdk/issues/714
I used to use that function without any issue previously. But maybe using the index version of the method is more intended for playlist uri's?

**Comment by undrtone** [comment]
Hi Nathan,

We updated to beta 20 this morning and also saw this error. In our case, it was because we were calling `playURI:startingWithIndex:callback:` before the `SPTAudioStreamingController` had finished logging in.

Previously, we used `loginWithSession:callback:` to know when the controller had finished logging in. Now, we learn that from the delegate function `<SPTAudioStreamingDelegate> audioStreamingDidLogin:`.

We also wondered if the function was intended for playlists, but the header doc does say to pass 0 for a single track.

Cheers,
michael

**Comment by NathanWalker** [comment]
Thanks @undrtone that makes sense. Will look into that. 👍

**Comment by bithavoc** [comment]
@undrtone is right, when the session is valid you still have to `loginWithAccessToken`:
```
 if ([self.auth.session isValid]) {
        // Use it to log in
        NSLog(@"Already authenticated with spotify");
        [self startLoginFlow]; // THIS IS WHAT THE TUTORIAL WANTS YOU TO DO BUT THE METHOD IS MISSING
    }
...
- (void)startLoginFlow {
   [self.player loginWithAccessToken:self.auth.session.accessToken];
}
```

**Comment by everythingswift** [comment]
Hello I'm trying to use beta 25 version for integrating Spotify SDK. I cannot get the basic player to work. 

Below is what works. 
1. OAuth flow is working fine. I've a test view controller, that launches OAuth view controller, I login using my spotify credentials, and I'm back into my app.
2. I've setup a notification to trigger on successful login that calls the below lines of code. However my delegate method for audioStreamingDidLogin never gets called back.

`        if self.player == nil {
            self.player = SPTAudioStreamingController.sharedInstance()
        }
        self.player!.delegate = self
        try! player?.start(withClientId: auth.clientID)
        self.player!.login(withAccessToken: authSession.accessToken)
`
No error messages seen on console.

**Comment by GokmenAkar** [comment]
@everythingswift Did you solve the problem? I have exactly same issue with beta 25.

**Comment by alex3144** [comment]
+1

**Comment by nanakchandra1** [comment]
I have facing same problem in beta 25
Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo={NSLocalizedDescription=The operation failed due to an unspecified issue.

I am using this method to play audio.

 @objc func play() {
        
        print(songInfo.uri)
        SpotifyManager.player?.playSpotifyURI(self.songInfo.uri.absoluteString, startingWith: 0, startingWithPosition: 0, callback: { (err) in
            
            print(err.debugDescription)

        })
    }

If anyone have solution for that issue please let me know.
