### ISSUE TITLE
New Frank Ocean album not streaming using SDK

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#753]
Since the album go reuploaded to spotify, even though the web API returns the tracks when queries from them, the SDK does not stream them.

Here's an example URI spotify:track:5RRbTnSvlD5AUYsQ1Cizor. It doesn't stream via the SDK.

Anyone else find this to be true?

**Comment by GabeJacobs** [comment]
It seems as though it works on the Android SDK, but it doesn't work on the iOS SDK

**Comment by sajsanghvi** [comment]
Same problem here

**Comment by GabeJacobs** [comment]
@Voxar Do you have any time to take a look at this. It's been bad the past few days since the album is such a hot topic.

**Comment by Voxar** [comment]
Hi

I have no problem on my end playing that track through the SDK. 

When albums are re-uploaded there will be new identifiers for the new versions, both album and tracks, and the old identifiers will "redirect" to the new ones. This redirection is an automated process working on music fingerprinting rather than manual mapping and it can therefore take some time before the album/track versions are processed matched. It also means that all tracks might not be available yet if you are playing from the old album identifier.

But my best guess is cached data and the problem should resolve itself as caches expire.

Do you experience the same problems still and even when you try with a clean install?

**Comment by matijse** [comment]
The songs plays fine in my iOS app (Now, did not test at the time of opening this issue)

**Comment by GabeJacobs** [comment]
@Voxar It works now. Closing the issue. I did experience the problems on a clean install over the course of the past few days. Any idea how we can avoid the issue in the future?
