### ISSUE TITLE
SPTSession isValid and SPTAudioStreamingController loggedIn reports wrong values

### ISSUE THREAD

**Issue by benji101** [spotify/ios-sdk#765]
## Description
After a successful login, calling isValid on SPTSession returns YES, but calling loggedIn on SPTAudioStreamingController returns NO.
After a logout, calling isValid on SPTSession still returns YES, and calling loggedIn on SPTAudioStreamingController still returns NO.

### Versions
iOS SDK beta 22.
Tested on simulator iOS 9.3
Tested on iPhone 6 Plus iOS 9.3.1

### Severity
Major, since it's not possible to determine session status.

## Steps to Reproduce
1. Using the DEMO app, add a breakpoint anywhere after successful login.
2. Inspect values of SPTSession isValid and SPTAudioStreamingController loggedIn.
3. Add a breakpoint after logout.
4. Inspect values of SPTSession isValid and SPTAudioStreamingController loggedIn.

### Actual behaviour
After login:
- calling isValid on SPTSession returns YES
- calling loggedIn on SPTAudioStreamingController returns NO

After logout:
- calling isValid on SPTSession returns YES
- calling loggedIn on SPTAudioStreamingController returns NO

### Expected behaviour
After login:
- calling isValid on SPTSession returns YES
- calling loggedIn on SPTAudioStreamingController returns YES

After logout:
- calling isValid on SPTSession returns NO (not sure about this one)
- calling loggedIn on SPTAudioStreamingController returns NO

**Comment by erdtman** [comment]
What you are describing is actually expected behavior. Let me explain. 
The session object represents the OAuth session independently from the player (SPTAudioStreamingController). You can use the session object (or the access token  from the session object) to log in the player. But you can also use the session object (access token) to access the web-api. When you logout the player it is intentionally not affecting the token that was used to log it in. So when you call isValid on the session object it will only check the expiration time of the session (token in the session) not if the player is logged in. With Beta 22 we tried to make this clearer by separating the usage so that the player only took a token and not a session.
