### ISSUE TITLE
getting a playlist's tracks with market argument

### ISSUE THREAD

**Issue by henrydeclety** [spotify/ios-sdk#806]
With the new version of sdk I can't find anyway of getting a playlist's tracks including a market arguments ..

**Comment by theorytank** [comment]
In my particular implementation I have a server calling the rest api in order to get the playlist's tracks.  I didn't see the market fields there either.  But if you pass in the market you get an "is_playable" field on the track that comes back.  I needed to filter those out (when false) otherwise the song wouldn't play in my iOS app.

I know it's not totally answering your question but maybe points you in a direction.  I only do playback using the iOS SDK, the searching is all done on the server side in my setup.

REST API Doc: https://developer.spotify.com/web-api/get-playlists-tracks/

**Comment by erdtman** [comment]
I'm sorry to say but the metadata library part has been deprecated. However the source code has been released, see https://github.com/erdtman/spotify-ios-metadata/
