### ISSUE TITLE
Why was the metadata framework deprecated?

### ISSUE THREAD

**Issue by edwinfinch** [spotify/ios-sdk#837]
Hi there, just a quick question.

Why was the metadata framework deprecated? Are there plans for a new framework we should brace ourselves for, or should we just maintain the metadata on our own?

Cheers

**Comment by erdtman** [comment]
As noted by some of you here, the iOS-SDK was not updated as often as you would wished in an attempt to limit the scope of the iOS-SDK we release the [source code](https://github.com/erdtman/spotify-ios-metadata/) for the metadata part, so that the community would have the opportunity to maintain it or write new wrappers for the web-api. 
Further the deprecation was part of work aligning iOS-SDK and Android SDK, on android there has never been a metadata library. The once that has exists for android has always been community developed and that has proven to work better.
